defaults:
  - model: vanilla_inr
  - train: default
  - data: default
  - optional experiment: null
  - _self_

seed: 42
project_name: anatcoder
experiment_name: "${model.name}_${data.case}_${data.n_views}views"
